#!/bin/bash
 # Collect the current user's ssh and enable passwords
 echo -n "Enter the username "
 read -s -e user
 echo -ne '\n'
 echo -n "Enter the password "
 read -s -e password
 echo -ne '\n'
 
# Feed the expect script a device list & the collected passwords
for device in `cat ~/F5_Check/F5_Host.txt`; do
 ./F5_Out_v1.exp $device $password $user ;
 done
