#!/bin/bash
 # Collect the current user's ssh and enable passwords
 echo -n "Enter the SSH password for $(whoami) "
 read -s -e password
 echo -ne '\n'
 
# Feed the expect script a device list & the collected passwords
for device in `cat ~/F5_Check/F5_Host.txt`; do
 ./F5_Out.exp $device $password ;
 done
